# Generated by Django 5.1.4 on 2024-12-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("alpha2", models.CharField(max_length=2)),
                ("alpha3", models.CharField(max_length=3)),
                ("region", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "countries",
                "managed": False,
            },
        ),
    ]
