# Generated by Django 5.1.4 on 2024-12-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countries",
            options={},
        ),
    ]
